### PR TITLE
Almost remove Emacswiki support

### PR DESCRIPTION
**Pull request by tarsius**
The Emacswiki is completely unsuitable as a source of automatically
generated and widely distributed packages.  Anyone can edit any
package on the Emacswiki without even having to create an account.

This is a huge security risk for the whole community.  And addressing
that is much more important than to avoid inconveniencing some users
by removing their favorite packages.  Just imagine the "inconvenience"
of your computer being taken over.

This commit removes support for updating or adding `wiki` packages,
but it does not completely remove support for such packages.  `wiki`
packages can continue to exist until we get around to removing them
for good.  This had the benefit that it becomes impossible to inject
new malware once this has been subtree-merged into Melpa, while buying
us some time to handle the removal of `wiki` packages more gracefully.
However, not immediately removing all such packages has the
disadvantage that existing malware, if any, continues to be
distributed on Melpa.

Also see https://github.com/melpa/melpa/pull/5008.

### CODE REVIEW

**Comment by purcell** [comment]
👍 👍

**Comment by tarsius** [comment]
You haven't merged this into Melpa yet. Do you want me to do it?

**Comment by purcell** [comment]
`master` here now contains the change which removed `darcs`, `fossil` etc., so I think we need to resolve those recipes first in MELPA before updating the `package-build` there. I can potentially rewrite things here to remove that change, though, then apply to MELPA. What do you think?

**Comment by tarsius** [comment]
> so I think we need to resolve those recipes first in MELPA

What further work does https://github.com/melpa/melpa/pull/4802 need? I think it is ready and that we lose very little by merging it.

https://github.com/melpa/melpa/pull/4802/commits/485e91f97dc9668a9507bf4715c07ffd71fd5c73 provides an overview of the affected packages and some numbers to put things into perspective.

**Comment by tarsius** [comment]
> I can potentially rewrite things here to remove that change

If you think that we cannot switch away from non-git/hg vcs just yet, then yes, do that. (I would just create a `tmp-melpa` branch here, revert the appropriate commit, and merge the result into the `melpa` repository.)

But I don't think that is necessary. The script I use to import the non-git/hg repositories into the Emacsorphange is trivial (see https://github.com/emacsorphanage/p), and you have commit access to that organisation, so even if I should disappear you could easily and with little effort keep those packages up-to-date.

Right now I am not updating these imports regularly, but once Melpa starts relying on them I would be happy to setup a cron job or similar.

I *think* there is even an additional benefit in switching to my imports (beside simplifying `package-build.el`): the packages would appear on Melpa stable also. My imports contain tags while the old fetchers did not support that for all vcs, I believe.

**Comment by milkypostman** [comment]
soooo, i accidentally deleted all packages. during setup of a new server (was doing too many things at once). so now all emacswiki packages  are dead....

**Pull request merged**
