### PR TITLE
method for package-recipe--working-tree

### PR DESCRIPTION
**Pull request by sharad**
generate repository path based on package name, which is posing multiple
clone or sync from same repository if there are multiple packages present in
same repository, which in turn consuming lot of CPU and disk-space

Modified method package-recipe--working-tree
to generate path based on repository url, to overcome this issue.

### CODE REVIEW

**Comment by tarsius** [comment]
Let's not do that. All this does is save a tiny bit of CPU and disk-space at the cost of known as well as unknown complications.

Just as an example: one complication is that it would no longer be trivial to go to the repository of a certain package. Also until now we could assume that a local repository always corresponds to exactly one repository and as a consequence we did not have to and did not think about complications that arise due to a repository belonging to multiple packages. There likely would be issues involving time travel.

**Comment by sharad** [comment]
Agreed, thanks

**Comment by sharad** [comment]
Agreed, thanks

**Comment by sharad** [comment]
Agreed, thanks

**Comment by sharad** [comment]
Agreed, thanks

**Pull request closed without merging**
